### ISSUE TITLE
Use of "syscall" in the package itself prevents use within Google App Engine

### ISSUE THREAD

**Issue by kujenga** [algolia/algoliasearch-client-go#103]
This PR https://github.com/algolia/algoliasearch-client-go/pull/95 introduced the use of the `syscall` package within the client library itself, where it was previously used just in test files.

The Google App Engine sandbox prevents the usage of several libraries within the stdlib, including `syscall`. Would it be possible to either move the use of `syscall` back to the tests, or use [`os.Getenv`](https://golang.org/pkg/os/#Getenv) instead? The checks of the "ok" return parameter from `syscall.Getenv` could just be replaced with a check for the empty string.

I'm happy to submit a PR doing so!

**Comment by aseure** [comment]
@kujenga Thank you for opening this issue. It's definitely not intended. I'lll open a PR right now to use the `Getenv` from the `os` package instead.

**Comment by aseure** [comment]
@kujenga I merged the PR. It should be OK now with Google App Engine as I replaced the `syscall` import with an `os` one.

Sorry for the inconvenience it may have caused and thank you again for reporting the issue.

**Comment by kujenga** [comment]
Perfect! Thanks so much for the quick response time, you guys are the best!
