### ISSUE TITLE
Cannot add objects which are not of type map[string]interface{}

### ISSUE THREAD

**Issue by nyeargh** [algolia/algoliasearch-client-go#13]
Using the following code will result in a panic stating `interface conversion: interface {} is main.Media, not map[string]interface {}`
```go
package main

import (
	"github.com/algolia/algoliasearch-client-go/algoliasearch"
)

type Media struct{}

func main() {
	client := algoliasearch.NewClient("******", "****************")

	index := client.InitIndex("media")

	m := Media{}

	index.AddObject(m)
}
```

This doesn't work well with my current system as the database schemas are built using structs and not maps.

However, using the following code will work absolutely fine.
```go
package main

import (
	"github.com/algolia/algoliasearch-client-go/algoliasearch"
)

type Media struct{}

func main() {
	client := algoliasearch.NewClient("******", "****************")

	index := client.InitIndex("media")

	m := Media{}

	index.AddObjects([]interface{}{m})
}
```

Do you know if you could add support for objects which are not just regular maps?

**Comment by Nagriar** [comment]
Hi @nyeargh,

I fixed the issue in addObject, the backend is able to extract the objectID from the body of the object so it's not important to extract it in the client.

Best regards

**Comment by nyeargh** [comment]
Perfect! Thanks for all the hard work. However when using the API more extensively, I noticed that other methods such as `UpdateObject` or `PartialUpdateObject` also had the same issue. They accept type `interface{}` but immediately try to convert that `interface{}` to a map and then access a key value. Ideally these methods should either strictly accept only maps or there should be some sort of function to extract the id from either a map or a struct using reflect.

**Comment by Nagriar** [comment]
@nyeargh What do you think about this solution to allow custom structure in the updateObject and partialUpdateObject?

**Comment by nyeargh** [comment]
Hm, it works on very basic things but it doesn't take into account struct tags. For instance, if I have a struct which looks like
```go
type User struct {
  UserID `json:"objectID"`
}
```
then the code would not find it. I feel like I'm nit-picking at this point, but not all objects with have the the `id` *and* the `name` field. A potentially better solution would be to use a completely custom tag such as so
```go
type User struct {
  UserID uint64 `json:"id" algoiaID:"true"`
}
```
Just an idea.

**Comment by Nagriar** [comment]
Hi @nyeargh,

Sorry for the late reply, I think a tag is definitely a better idea but I would prefer to use the tag `json:"objectID"` because in the case of batch or addObject, we don't need to have a special handling to forward the objectID to the backend. It's already done by the json.

What do you think?

**Comment by nyeargh** [comment]
I think that's a potential solution, it's what I was doing initially with batch insertion. However, this then leads to users being forced into using `objectID` on all their clients. Meaning that it's going to require more effort to integrate algolia into an already existing system.

I guess it works though as this is the standard set in all other clients as well, but it'd be nice to have the flexibility of having clients use whatever tag they want for IDs and then just include a tag in the struct to indicate what field is the algolia ID.

**Comment by nyeargh** [comment]
After some more use building servers, I'm *really* thinking that the `algolia:"true"` kind of solution is the best idea here. I really don't want to have to use `objectID` when serving content to clients just because algolia uses it. I guess that's just my preference though...

**Comment by aseure** [comment]
Hello @nyeargh. Sorry for the late follow up but I wanted to let you know that we've released the v2 of the Go client.

About what you proposed, we've decided to use a `map[string]interface{}` (actually an `algoliasearch.Object` type) to manipulate objects you can send/retrieve to/from Algolia. We acknowledge it may have other solutions but we discussed about it and decided that it was most straightforward for the final user compared to forcing him to add additional tags to a `struct`.

If you need help with the migration of your code, we've compiled all the changes on [this wiki page](https://github.com/algolia/algoliasearch-client-go/wiki/Migration-guide-to-version-2.x). If you still need help, we would be happy to help you. Just contact us at support@algolia.com or open an issue on Github if you think it's implementation-related.
