### ISSUE TITLE
AWS Lambda: socket: too many open files

### ISSUE THREAD

**Issue by sorenbs** [algolia/algoliasearch-client-go#287]
I am consuming events from a kinesis queue in a lambda function and calling

```go
algoliaIndex := algoliaClient.InitIndex(lambdaEvent.IndexName)
_, algoliaOperationError = algoliaIndex.AddObjects(objectsToSync(lambdaEvent))
```

After 6,930 successful calls I get the following error:

```
Cannot perform request [POST] /1/indexes/SyncItem/batch (8OVNLPT6JS-1.algolianet.com): Post https://8OVNLPT6JS-1.algolianet.com/1/indexes/SyncItem/batch: dial tcp: lookup 8OVNLPT6JS-1.algolianet.com on 10.15.0.2:53: dial udp 10.15.0.2:53: socket: too many open files
```

Is it possible that the Algolia go library doesn't correctly close old connections or am I missing something?

**Comment by sorenbs** [comment]
Comment from the https://github.com/eawsy/aws-lambda-go maintainer

```
@sorenbs AWS Lambda is not freshly initialized each time you invoke it. One Lambda can persist over the time (nearly 8 hours) before being recycled. So when I see your error, it seems that you orthe algolia lib have forgotten something like defer foo.Close() somewhere. Thus, over the time the number of opened sockets grows and the error occur. But without more info, this is just an intuition.
```

**Comment by aseure** [comment]
Hello @sorenbs. Sorry to hear you're experiencing this issue.

Could you tell me what is the Go client version/commit hash you are currently using in your lambda instance?

**Comment by fsenart** [comment]
Voila :)

**Comment by sorenbs** [comment]
@fsenart - you are amazing :-)

@aseure - I am using latest master

**Comment by sorenbs** [comment]
@aseure - how quickly are you usually able to merge prs? Is it reasonable to expect it could happen today, or should I rather go ahead and use the branch for now?

**Comment by aseure** [comment]
@sorenbs Merged and version bumped to `2.7.1` on `master`.

@fsenart Thank you again for the fix.

**Comment by aseure** [comment]
@sorenbs Could you confirm me that the problem is fixed on your side? I'll wait for that to close your issue.

**Comment by sorenbs** [comment]
It looks like this did indeed solve the issue. Thanks a lot both!

**Comment by aseure** [comment]
Good to know and sorry for the inconvenience it may have caused.

**Comment by sorenbs** [comment]
No problem.

This might be unrelated, but I am seeing a new network error:

```
Cannot perform request [POST] /1/indexes/SyncItem/batch (81EKEB57VQ-1.algolianet.com): Post https://81EKEB57VQ-1.algolianet.com/1/indexes/SyncItem/batch: dial tcp: lookup 81EKEB57VQ-1.algolianet.com on 10.11.0.2:53: no such host
```

Out of 10k requests I get this error 26 times.

I have added retry logic to get around this, but anything you can add to enlighten me would be appreciated.

**Comment by aseure** [comment]
It seems like a DNS request issue, probably due to your environment and beyond the scope of what our API clients can do. Internally, we are using a fallback solution in such situation to select another host from your Algolia cluster, so even if you experience DNS lookup issues from time to time, you should eventually connect, without your external retry logic. If it's not the case, let me know and I'll investigate more.

**Comment by kottuvishnu** [comment]
I am having the same issue, How can I close all foo.Close() method in C# .net core AWS Lambda

**Comment by rslangham** [comment]
> I am having the same issue, How can I close all foo.Close() method in C# .net core AWS Lambda, I am using AmazonKinesisFirehoseClient to send data to Kinesis, there my code is breaking

@kottuvishnu did find solution, we are having big issue with open files with .net core and lambda.  Curious if there is a way to actually determine what files handles may still be open at the end of the execution?

**Comment by kottuvishnu** [comment]
@rslangham  My issue got resolved after increasing the memory size of the lambda in the AWS console, try increasing the memory size of the lambda

**Comment by rslangham** [comment]
> @rslangham My issue got resolved after increasing the memory size of the lambda in the AWS console, try increasing the memory size of the lambda

thank you,  I don't believe this is going to solve our issue,  we increased significantly for other tests and still seeing issue.  we may need to upgrade many of our nuget packages in hope to get any bug fixes in this area

**Comment by rslangham** [comment]
tracked down our issue, we are using Redis and the StackExchange Redis driver v1.2.   Determined that it was the cause of the handle leak.   Upgraded the driver to the v2.0 for .net core and the problem was resolved.
