### ISSUE TITLE
GetLogs ignores params

### ISSUE THREAD

**Issue by hugecannon** [algolia/algoliasearch-client-go#321]
GetLogs method takes params as a `Map` and passes them down the request flow.

[func (c *client) GetLogs(params Map)](https://github.com/algolia/algoliasearch-client-go/blob/master/algoliasearch/client.go#L136)

In [buildRequest](https://github.com/algolia/algoliasearch-client-go/blob/master/algoliasearch/transport.go#L290) there should be a check to see if method type is `GET`, then translate `body` into query parameters.

**Comment by aseure** [comment]
Hello @hugecannon,

Thank you for opening this issue. I've checked and you are right, the URL parameters were not passed correctly. I've implemented the fix you suggested on https://github.com/algolia/algoliasearch-client-go/pull/322 which should be merged and tagged today on the `master` branch. The test for `GetLogs` wasn't showing the issue so I rewrote it too.

I'll close this issue when the PR will me merged on master. Feel free to re-open it if needed.

Thank you again for your contribution.

**Comment by aseure** [comment]
Fixed as of [2.14.0](https://github.com/algolia/algoliasearch-client-go/releases/tag/2.14.0)

**Comment by hugecannon** [comment]
Thanks @aseure
