### ISSUE TITLE
Add functions waiting for server completion

### ISSUE THREAD

**Issue by ercolanelli-leo** [algolia/algoliasearch-client-go#37]
Most of the time the user wants to wait for the settings to be effective on the server before continuing,
it may be a good idea to add convenience functions that include the "waiting" part.

**Comment by redox** [comment]
Are you speaking about `WaitTask`? (https://github.com/algolia/algoliasearch-client-go/blob/f2906a841ae2393fcfaf354377092ed960968f30/algoliasearch/index.go#L89-L96)

**Comment by ercolanelli-leo** [comment]
Yes! Making convenience function doing directly AddObject + WaitTask, or SetSettings + WaitTask for example.
Error checking in Go is space consuming so it would save 4/5 lignes each time if one decide to add and the wait.

**Comment by aseure** [comment]
@ercolanelli-leo Why did you close it?

**Comment by ercolanelli-leo** [comment]
After a discussion with @redox it's actually not necessary at all because of the way jobs are queued
