### ISSUE TITLE
Check if (and when) `Index`/`Length`/`Offset` are still part of `QueryRes`

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-go#380]

**Comment by aseure** [comment]
I've checked the code and the received JSON responses. `QueryRes` is currently used:
 - As a response for the `Search` function
 - As a response for the `Browse` functions
 - As a response for the `MultipleQueries` function

For all those function calls, I cannot find a single mention in the JSON returned by the API of `length` and `offset` and `index` is only found in the context of `MultipleQueries` response, hence it doesn't have to exist in the `QueryRes`.

cc @julienbourdeau @maxiloc If you guys confirm, I'm gonna remove those 3 fields from `QueryRes`.

**Comment by julienbourdeau** [comment]
I have never seen offset, length and index. This is unusual naming for the core api tbh but more usual in the analytics api. I think it's safe to remove them 👍

**Comment by maxiloc** [comment]
Yep does not ring a bell on my side. I would still double check with someone from the search api team.

**Comment by aseure** [comment]
Thanks for confirming buddies.

@maxiloc Don't spend your time on that, I planned to do it after :)

**Comment by q-litzler** [comment]
I have seen `index` for sure. I can't quite remember exactly the use case, but a wild guess would be: Check when a abTest is active on the index.

**Comment by maxiloc** [comment]
> I have seen index for sure. I can't quite remember exactly the use case, but a wild guess would be: Check when a abTest is active on the index.

I think it's `indexUsed`

**Comment by aseure** [comment]
@maxiloc `indexUsed` yes and it's already handled. However I have the same feeling as @q-litzler, I'm pretty sure I've seen `index` as part of the response elsewhere, I just don't know when/how to trigger it. For `length` and `offset`, I'm a bit more clueless.

**Comment by aseure** [comment]
@pp5x rocks

The `length`/`offset` parameters are available when a search query is issued along with **both `offset` and `length` parameters** as query parameters, as documented in the [search query paramater doc](https://www.algolia.com/doc/api-reference/api-parameters/length/?language=go#impact-on-the-response).

Next step is to document that in the [Search method response fields](https://www.algolia.com/doc/api-reference/api-methods/search/?language=go#response) as well.

**Comment by aseure** [comment]
Oups @pp5x did it again...

`index` is actually available as a response fields when performing a `MultipleQueries` call [as ~hidden~ documented here](https://www.algolia.com/doc/api-reference/api-methods/multiple-queries/?language=go#method-response-index).

Closing this issue as both fields should be exposed as it was the case originally. Keeping track of the implementation in other typed clients in https://github.com/algolia/algoliasearch-client-specs/issues/17.

**Comment by julienbourdeau** [comment]
I was reading the doc and noticed it's sort of documented: https://www.algolia.com/doc/api-reference/api-methods/search/?language=javascript#method-response-nbpages :D

**Comment by aseure** [comment]
Thanks for the extra link @julienbourdeau
