### ISSUE TITLE
Expose `id` string in `SaveRuleRes`

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-go#397]

**Comment by aseure** [comment]
@maxiloc 
Weird behaviour detected here:
 - Even though the `objectID` field is `Required` [according to the documentation](https://www.algolia.com/doc/api-reference/api-methods/rules-save/?language=javascript#parameters), I can save a rule without defining it
 - If I provide the field, I don't have [the `id` field](https://www.algolia.com/doc/api-reference/api-methods/rules-save/?language=javascript#response) in the raw JSON response
 - If I don't provide it, I still do **not** have the `id` field in the raw JSON response but I get `"objectID":"rules"` and it's always the same, even after multiple calls.

Any idea why? Should we document the field and/or rename it? If you don't have any clue, I'll ask Search API Squad.

**Comment by maxiloc** [comment]
The endpoint is `/1/indexes/{indexName}/rules/{objectID}` so objectID is should be required.

**Comment by aseure** [comment]
After investigations, we have discovered that calling the [`Save a single rule` endpoint](https://www.algolia.com/doc/rest-api/query-rules/#save-a-single-rule) with an empty `objectID` field for the rule is interpreted by the engine as a new record to index, whose `objectID` is `rules`, which maps to [`Add/Update an object by ID` endpoint](https://www.algolia.com/doc/rest-api/search/?language=javascript#addupdate-an-object-by-id).

In other words, instead of saving a new rule with `/1/indexes/{indexName}/rules/{objectID}` with an empty `objectID` (even in the presence of the trailing slash after `rules`), we were actually calling `/1/indexes/{indexName}/{objectID}` with `objectID` set to `rules`, creating a new record instead.

As this routing issue cannot be fixed server-side, we will have to enforce it client-side, by checking that the given `objectID` is not empty. Same applies for all other API clients.

Thank you for helping me investigate @clement-leprovost and @Nagriar.

@maxiloc Regarding the original issue, I confirm that after a `SaveRule` call the expected response is only composed of the `taskID`/`updatedAt` fields, [as correctly documented here (REST API)](https://www.algolia.com/doc/rest-api/query-rules/?language=javascript#response) and [incorrectly documented here (API method)](https://www.algolia.com/doc/api-reference/api-methods/rules-save/?language=javascript#response) (see LINK for the related issue in the documentation repository).
