### ISSUE TITLE
Cannot go get

### ISSUE THREAD

**Issue by seenickcode** [algolia/algoliasearch-client-go#4]
````
go get
# github.com/algolia/algoliasearch-client-go/algoliasearch
../../algolia/algoliasearch-client-go/algoliasearch/Transport.go:110: t.httpClient.Transport.(*http.Transport).TLSHandshakeTimeout undefined (type *http.Transport has no field or method TLSHandshakeTimeout)
../../algolia/algoliasearch-client-go/algoliasearch/Transport.go:183: t.httpClient.Transport.(*http.Transport).TLSHandshakeTimeout undefined (type *http.Transport has no field or method TLSHandshakeTimeout)
````

**Comment by Nagriar** [comment]
Which version of Go are you using?

**Comment by seenickcode** [comment]
1.2 I believe.

It works on my OSX machine but that machine has a newer version

**Comment by Nagriar** [comment]
Yes it's the issue, we dropped the support of Go 1.2 in order to be able to set a timeout for the http requests.

You can run "go version" to know your version.

**Comment by seenickcode** [comment]
It's 1.2.1.
You should cite that version support in the top of the README for everyone to see maybe?

**Comment by Nagriar** [comment]
You're totally right, I just added the supported version in the Readme, thanks for the feedback!
