### ISSUE TITLE
restrictHighlightAndSnippetArrays missing from settings

### ISSUE THREAD

**Issue by bpicolo** [algolia/algoliasearch-client-go#400]
Was toying around with programatic index settings and noticed a couple issues. Looks like this param is not in the current settings struct.
https://www.algolia.com/doc/api-reference/api-parameters/restrictHighlightAndSnippetArrays/

https://github.com/algolia/algoliasearch-client-go/blob/master/algoliasearch/types_settings.go#L11

This is also true for PaginationLimitedTo:
https://www.algolia.com/doc/api-reference/api-parameters/paginationLimitedTo/

**Comment by bpicolo** [comment]
Also: maxFacetHits is missing from ToMap()

**Comment by aseure** [comment]
Hello @bpicolo. Thank you for taking the time to open this issue. You were indeed right, `restrictHighlightAndSnippetArrays`, `paginationLimitedTo` and `maxFacetHits` were not correctly exposed. I've made the changes that will eventually be merged and released soon.

Thank you again for your contribution, I'll ping you on this issue once the release will have been done.

**Comment by aseure** [comment]
@bpicolo
Changes have been released as part of [2.12.2](https://github.com/algolia/algoliasearch-client-go/blob/master/ChangeLog.md#2212-2018-02-05). Thank you again for your contribution.

**Comment by bpicolo** [comment]
@aseure  Thanks for the quick turnaround : )
