### ISSUE TITLE
Expose `indexes` in get API key / keys

### ISSUE THREAD

**Issue by bpicolo** [algolia/algoliasearch-client-go#403]
Looks like this is present for API retrieve calls if set
python client:
```
c.get_api_key_acl('SECRET')
{u'description': u'Search-only API Key', u'validity': 0, u'indexes': [u'test-index-2'], u'value': u'SECRET', u'acl': [u'search'], u'createdAt': 1517349540}
```

**Comment by aseure** [comment]
Thank you again for your contribution @bpicolo. Your fix has been released as part of [2.21.3](https://github.com/algolia/algoliasearch-client-go/blob/master/ChangeLog.md#2213-2018-02-13). Have a good day.
