### ISSUE TITLE
Support to set http.Transport when new client

### ISSUE THREAD

**Issue by idy** [algolia/algoliasearch-client-go#408]
Current implementation of algolia client creates a new `http.Transport` for every single new Algolia client. This is highly inefficient from connection management perspective.  Given the only difference between  algolia clients are the authentication headers on all outbound requests, the underlying connections to algolia API server can be pooled/reused if a single `http.Transport` is used.

**Comment by aseure** [comment]
Hello @idy,

Thank you for starting this discussion regarding the possibility to share HTTP clients between multiple instances of the Go client. I agree that instantiating a new HTTP client for every Algolia client may seem overkill.

Currently, as of the `v2` version, you may use the `Client.SetHTTPClient(...)` to override the Client HTTP transport layer and hence use shared HTTP client between each instances.

We are currently working on a new major version (currently `v3.0.0-beta01`) which addresses the issue differently as you're gonna be able to replace the default HTTP layer when instantiating the Algolia Client instead. More information on that when we will release the migration guide.

I hope this helps. Feel free to reopen this issue if you need further assistance on how to re-use the same HTTP client for multiple instances of the Algolia client.
