### ISSUE TITLE
Missing parameters

### ISSUE THREAD

**Issue by maxiloc** [algolia/algoliasearch-client-go#438]
**settings**

- [x] [disablePrefixOnAttributes](https://www.algolia.com/doc/api-reference/api-parameters/disablePrefixOnAttributes/)
- [x] [disableExactOnAttributes](https://www.algolia.com/doc/api-reference/api-parameters/disableExactOnAttributes/)
- [x] [exactOnSingleWordQuery](https://www.algolia.com/doc/api-reference/api-parameters/exactOnSingleWordQuery/)

**search**

- [x] [optionalFilters](https://www.algolia.com/doc/api-reference/api-parameters/optionalFilters/)
- [x] [ruleContexts](https://www.algolia.com/doc/api-reference/api-parameters/ruleContexts/)

**Comment by aseure** [comment]
Good catch, thanks @maxiloc. I've already started a branch for the missing settings parameters while writing the tests. I'll add the search parameters as well.

For the record, the Go client doesn't prevent you from using the missing parameters, the only thing is that it won't prevent you to pass the wrong type to the engine (i.e. getting clean error before the HTTP call vs. getting a weird error from the engine after the HTTP call).
