### ISSUE TITLE
Add a method to the client to extend (not override) the User-Agent header

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-go#441]

**Comment by julienbourdeau** [comment]
Ideally, it should be static, so set for all instance of the client. Typically, in a framework integration, we add the framework details at the beginning and then any client instanciated will have these details.

The way it works in PHP: 

https://github.com/algolia/algoliasearch-client-php/blob/2.0/src/Support/UserAgent.php#L22-L26

https://github.com/algolia/algoliasearch-client-php/blob/2.0/src/RequestOptions/RequestOptionsFactory.php#L81

**Comment by aseure** [comment]
Closed in favor of https://github.com/algolia/algoliasearch-client-specs/issues/16.
