### ISSUE TITLE
Hidden x509 error when using Docker

### ISSUE THREAD

**Issue by sjdweb** [algolia/algoliasearch-client-go#445]
This is not necessarily a bug report, but there is not much information when this error occurs for me in Docker.

## Steps to reproduce
- Run a Go app using algolia-client-go in Docker, I'm using Debian stretch which probably has a lot to do with it
- Your output during any call will be:
```
All hosts have been contacted unsuccessfully
```

## What's actually happening
Using `ALGOLIA_DEBUG=2` I found that there was an SSL issue
```bash
docker run -e ALGOLIA_DEBUG=2 --rm -it mystuff/mysvc
```
Output
```
* RESPONSE [0] err=cannot perform request GET https://XXXX-dsn.algolia.net/1/indexes: Get https://XXX-dsn.algolia.net/1/indexes: x509: failed to load system roots and no roots provided body=
```

I see two problems here:
- Until you make a call, you don't get an error, which means `.NewClient()` and `.InitIndex()` do not fail early on
- The x509 error is not surfaced and I spent an hour thinking it was DNS or some issue

**Comment by Silver-birder** [comment]
me too.
but, I was missing the following steps:

```
export ALGOLIA_INDEX_KEY=xxx
export ALGOLIA_APP_KEY=xxx
export ALGOLIA_ADMIN_KEY=xxx
```
Then I succeeded 😆

**Comment by aseure** [comment]
Hello @sjdweb,

Thank you for submitting this issue.

First of all, could you double check that you correctly passed the applicationID when instantiating the search client?

My second guess is that your Debian certificates are outdated in your Docker container. Could you try to install or update them using `sudo update-ca-certificates`? This is a fairly common issue when working with Docker containers, I've been there as well :) I've also found this page that describes in details this issue if you're interested: https://docs.docker.com/ee/dtr/user/access-dtr/.

Feel free to close this issue if your problem have been solved already.

Have a nice day.

**Comment by oshanz** [comment]
Thanks, @aseure for the tip

My application threw `500 Internal Server Error` when running inside a `docker.io/debian:bullseye` container.

```json
{"error":"all hosts have been contacted unsuccessfully, it can either be a server or a network error or wrong appID/key credentials were used. You can use opt.ExposeIntermediateNetworkErrors(true) to investigate.","status":false}
```

the solution is you have to install `ca-certificates`
```dockerfile
FROM docker.io/debian:bullseye

RUN apt-get update && apt-get install -y ca-certificates && rm -rf /var/lib/apt/lists/*
```
