### ISSUE TITLE
Index.getObjects returns Nil when object ID contains url-encodable symbols

### ISSUE THREAD

**Issue by pavel-popov** [algolia/algoliasearch-client-go#456]
- Algolia Client Version: 2.25.0
- Language Version: go1.11

### Description

We have objects with IDs constructed like `k:v`, for example `place:12345`. For such objects I can get objects by ID in the Dashboard, but the result from `Index.GetObjects` method is always `nil`. The reason for this is that `url.QueryEscape` is applied to object id which is sent within POST Body, hence it's not url-decoded on the receiver side.

`Index.GetObject` method works as expected.

### Steps To Reproduce

1. Add object with `objectID="temp:123"`
2. Query it using `Index.GetObjects([]string{"temp:123"})`

**Comment by aseure** [comment]
Thank you for reporting this issue @pavel-popov. This has been fixed and released as of `v2.28.0`. Also, our next `v3.0.0-beta02` and above will also have it fixed.

Thanks again for taking the time to report this issue.
