### ISSUE TITLE
Add: IndexSettings -> userData

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-go#484]
`userData` is now a property of `IndexSettings`

**Comment by aseure** [comment]
@Ant-hem any official document about the format of `userData` in the context of the `settings`? Also, is this a "setable" property?

**Comment by Ant-hem** [comment]
> @Ant-hem any official document about the format of `userData` in the context of the `settings`? Also, is this a "setable" property?

@maxiloc told me last week that `userData` could be any JSON object (nothing is enforced by the engine). And yes it's settable.
