### ISSUE TITLE
Add -> primary parameter in IndexSettings

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-go#487]
The `primary` parameter keeps track of which primary index (if any) a replica is connected to.

Type: `String`
**Only getable**  on the `IndexSettings` of a replica.

**Comment by aseure** [comment]
Closing as it's already available [as of 3.0.0](https://github.com/algolia/algoliasearch-client-go/blob/v3.0.0/algolia/search/settings.go#L23). However, because of the way we generate the settings, we cannot make it read-only.
