### ISSUE TITLE
Serialization of nested arrays in URL params

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-go#488]
We should make sure that `Query` with **nested arrays** parameters are serialized this way when used as a URL params. (Like for example in `MultipleQueries`)

For example with `facetFilters`: 
`facetFilters=[["a:true"],["b:false"]]`

**Comment by aseure** [comment]
Closed by https://github.com/algolia/algoliasearch-client-go/pull/499
