### ISSUE TITLE
search.IndexInterface missing Exists()

### ISSUE THREAD

**Issue by i0exception** [algolia/algoliasearch-client-go#537]
search.IndexInterface is missing the Exists() function - could this be added? makes mocking easier.

https://github.com/algolia/algoliasearch-client-go/pull/513 changed index.go but not index_interface.go

**Comment by aseure** [comment]
@i0exception Thank you for opening this issue. Great catch indeed. I've just fixed it in #538 and it's now released in [v3.2.1](https://github.com/algolia/algoliasearch-client-go/blob/master/ChangeLog.md#v321-2019-08-21). You should be able to update now!

Have a nice day.
