### ISSUE TITLE
# feat(search): explain decompounding at query time

### ISSUE THREAD

**Issue by Ant-hem** [algolia/algoliasearch-client-go#560]
Please add the following modifications to both `query` and `searchReponse` objects

**Addition to existing JSON schemas**

Query: new optional parameter `explain` (or not new if Query Rules v2 was already implemented)

```java
{
  "explain": string[]?
}
```

SearchResponse: new `explain` response field (or not new if Query Rules v2 was already implemented)

```java
        "explain": {
            "match": {
                "alternatives": [
                    {
                        "type": string,
                        "words": string[],
                        "typos": int,
                        "offset": int,
                        "length": int
                    }
                 ]
            }
         }
```

**Comment by aseure** [comment]
Closing this one since `explain` was already implemented as part as the Query Rules v2 feature. The response object doesn't need to be changed for now since we only return a generic map in the Go client, so this new `match` is already accessible.
