### ISSUE TITLE
Not possible to create Query Rule triggered only by empty query

### ISSUE THREAD

**Issue by JanPetr** [algolia/algoliasearch-client-go#572]
- Algolia Client Version: 3.5.0
- Language Version: go1.13.3 darwin/amd64

### Description

Hello team! 👋 

I need to create query rule for an empty query with Go API client. However, I’m getting `Algolia API error [400] Missing mandatory pattern (condition.pattern) (in [88]) (near 1:68469)` from the API. 

I believe it’s due to [`json:"pattern,*omitempty*"`](https://github.com/algolia/algoliasearch-client-go/blob/master/algolia/search/rule_condition.go#L7), which removes the pattern completely from generated JSON and therefore API rejects the call, and was introduced by https://github.com/algolia/algoliasearch-client-go/commit/f2cdcdd582adaa58f4ad50edd449485a5b390229 in 3.5.0 version of the client.

In [documentation](https://www.algolia.com/doc/api-reference/api-methods/save-rule/#method-param-pattern) I found that `""` pattern should be allowed:

> This parameter goes hand in hand with the anchoring parameter. If you're creating a Rule that depends on a specific query, you must specify the pattern and anchoring. The empty "" pattern is only allowed when anchoring is set to is.

However it doesn’t work for me and I didn’t manage to find the corresponding code, which should handle the pattern based on `anchoring.Is` 😕 

### Steps To Reproduce
Try to push query rule with condition:
```go
Condition: search.RuleCondition{
	Anchoring: search.Is,
	Pattern:   "",
},
```

Thanks for taking a look!

**Comment by aseure** [comment]
Thanks for reporting this @JanPetr. This is indeed a bug we will fix.

Since all condition's fields can be omitted, we will fix that by writing a custom `MarshalJSON()` function for the `search.RuleCondition`. We'll keep you posted on the upcoming PR.

**Comment by JanPetr** [comment]
Thanks @aseure!
