### ISSUE TITLE
Context Support

### ISSUE THREAD

**Issue by wedneyyuri** [algolia/algoliasearch-client-go#578]
- Algolia Client Version: v3.5.0
- Language Version: go1.13

### Description
Do you have any plans to introduce context (https://golang.org/pkg/context) support? Seems like there's no way to abort individual requests using this mechanism.

Context use cases go beyond a strict timeout. For example, they can be used for gracefull shutdown cases or in request proxies.

### Steps To Reproduce
```golang
type Contact struct {
  ObjectID  string `json:"objectID"`
  Firstname string `json:"firstname"`
  Lastname  string `json:"lastname"`
}

contacts := []Contact{
  {ObjectID: "myID1", Firstname: "Jimmie", Lastname: "Barninger"},
  {ObjectID: "myID2", Firstname: "Ray", Lastname: "Charles"},
}

res, err := index.SaveObjects(contacts) // <== how to use Context here?
```

**Comment by aseure** [comment]
Hello @wedneyyuri,

We've just released we didn't documented it in our [v2 to v3 upgrade guide](https://www.algolia.com/doc/api-client/getting-started/upgrade-guides/go/#upgrade-from-v2-to-v3) but this is actually a new feature of the v3 client: `context.Context` are already natively supported. You can pass them to any method as an extra variadic parameter such as:

```go
ctx, cancel := context.WithTimeout(context.Background(), 1*time.Second)
res, err := index.SaveObjects(contacts, ctx)
```
