### ISSUE TITLE
Invalid integer type for parsing BatchRes

### ISSUE THREAD

**Issue by ViBiOh** [algolia/algoliasearch-client-go#591]
- Algolia Client Version: 3.6.0
- Language Version: golang

### Description

I've got an error while deleting index, running client on a 32 bits ARM architecture (Raspberry Pi4 with Raspbian, so not 64 bits.).

The number returned by API seems to be an int64, but defined as an [int](https://github.com/algolia/algoliasearch-client-go/blob/master/algolia/search/responses_tasks.go#L18).

It works on 64 bits architecture, as int is an int64 on this kind of machine.

```
cannot deserialize response's body: json: cannot unmarshal number 116817924001 into Go struct field DeleteTaskRes.taskID of type int
```

### Steps To Reproduce

Simple case:
https://play.golang.org/p/TXNc0T-PUoz

Change `int` to `int64`, and it works.

Real case (on a 32bits architecture):

```go
client := search.NewClient(app, key)
index := client.InitIndex(indexName)

if _, err := index.Delete(); err != nil {
	log.Fatal(err)
}
```

**Comment by aseure** [comment]
Thanks for reporting this. Task IDs are indeed representable up to 2^53 (maximum integer of JSON numbers) and hence should be handled via 64b integers. PR #599 is fixing this!
