### ISSUE TITLE
Make clearIndex and deleteIndex at the client level

### ISSUE THREAD

**Issue by Nagriar** [algolia/algoliasearch-client-go#61]
Currently we have move and copy index in the client class does it make sense to also have clear and delete index in the same class?

**Comment by aseure** [comment]
@Nagriar I'm OK with adding a `Clear` method to the `Index`. However, I prefer not to add the `Delete` method as it would mean we could do `index.Delete()` and after that continue to access the `index` instance. Not a good idea IMO. What do you think @ercolanelli-leo?

**Comment by aseure** [comment]
Ok on it.

**Comment by Nagriar** [comment]
@aseure for example when you perform a full reindexing you do

```tmp_index.Delete()
tmp_index.Batch(...)
tmp_index.copy('prod')```
