### ISSUE TITLE
Ensure consequence.params.ignorePlurals can be deserialized from string

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-go#610]
It was discovered that the Algolia Search API is sometimes returning the
`ignorePlurals` field from a Query Rule's consequence params field as a
string, such as:

```json
"consequence": {
    "params:" {
        "ignorePlurals": "false"
    }
}
```

Could you please ensure that the deserialization of query rules coming from
`getRule`, `getRules`, `browseRules` are correctly decoding those strings
without failing.

Also, like we did for other string-based booleans, it would be convenient to
convert the string to an actual boolean when the string is equal to "true" or
"false".

**Comment by millotp** [comment]
Hey, this will be fixed in version 4.2.3 thanks to https://github.com/algolia/api-clients-automation/pull/3620, sorry for the loooong delay 😅
