### ISSUE TITLE
Use the same naming than in the other api client for the api key methods

### ISSUE THREAD

**Issue by Nagriar** [algolia/algoliasearch-client-go#62]
In the other api clients the naming of the functions are: (add|update|delete)UserKey and in go we use (add|update|delete)Key. Do we want to use the v2 to also normalize the naming?

**Comment by aseure** [comment]
@Nagriar As you said, normalisation is better. Could you just tell me if it only applies to the `Index` methods, not to the `Client` ones?

**Comment by Nagriar** [comment]
Both at the index and client level.

**Comment by aseure** [comment]
Ok on it. :)
