### ISSUE TITLE
Missing optional attributes in the BrowseRes

### ISSUE THREAD

**Issue by Nagriar** [algolia/algoliasearch-client-go#69]
We have an attribute "warning" used to indicate when the browse use a cursor based on a old version of the index.

**Comment by aseure** [comment]
@Nagriar Could you give me more details about this attribute? More specifically, the type and how to get it (what does "old version of the index" means)?

**Comment by Nagriar** [comment]
it's a string and you'll have it if you increase the version of the internal datastructure.

"old version of the index" means the engine generated another version  of the index between the call to get the cursor and the call to use it.
