### ISSUE TITLE
Supply a custom http.Client

### ISSUE THREAD

**Issue by SkippyZA** [algolia/algoliasearch-client-go#695]
- Algolia Client Version: v3.25.0
- Language Version: go1.18.3

### Description

I am implementing Algolia with AWS, and as part of our infrastructure, we make heavy use of AWS X-Ray for our distributed tracing. In order for x-ray to trace outgoing HTTP requests, a custom `http.Client` is required (https://docs.aws.amazon.com/xray/latest/devguide/xray-sdk-go-httpclients.html). Looking at the code and docs, I don't see the ability to provide your own `http.Client` instance to Algolia Search.

### Steps To Reproduce

N/A

**Comment by samouss** [comment]
Hello! The request layer is hidden behind the [`Requester`](https://github.com/algolia/algoliasearch-client-go/blob/2b2b5241b97cdf0d6e1751ba096c1904df19b813/algolia/transport/requester.go#L42-L44) interface. You can provide your own `Requester` implementation and most of the time this implementation relies on the `http.Client`. That's what we do in the in the client: we have a `defaultRequester` relying on `http.Client` implementing the `Requester` interface:

https://github.com/algolia/algoliasearch-client-go/blob/2b2b5241b97cdf0d6e1751ba096c1904df19b813/algolia/transport/requester.go#L46-L58

You can provide a custom `Requester` with the like this:

```go
type requester struct {
	client *http.Client
}

func (r *requester) Request(req *http.Request) (*http.Response, error) {
	return r.client.Do(req)
}

func run() error {
	r := &requester{
		client: &http.Client{},
	}

	client := search.NewClientWithConfig(search.Configuration{
		AppID:     "appID",
		APIKey:    "apiKey",
		Requester: r,
	})

	return nil
}
```
