### ISSUE TITLE
There is no way to set empty array to `attributes_to_highlight`

### ISSUE THREAD

**Issue by k-yomo** [algolia/algoliasearch-client-go#704]
- Algolia Client Version: master
- Language Version: v1.19

### Description
Setting `opt.AttributesToHighlight()` result in `null` not empty array since nil array will be marshaled to `null` in JSON.
```go
func main() {
	test()
	// => "null"
}

func test(v ...string) {
	b, _ := json.Marshal(v)
	fmt.Println(string(b))
}
```

### Steps To Reproduce
```go
func main() {
	algoliaSearchClient := search.NewClient(os.Getenv("ALGOLIA_APP_ID"), os.Getenv("ALGOLIA_API_KEY"))
	index := algoliaSearchClient.InitIndex("highlight-test")
	res, err := index.SetSettings(search.Settings{
		AttributesToHighlight: opt.AttributesToHighlight(),
	})
	if err != nil {
		panic(err)
	}
	if err := res.Wait(); err != nil {
		panic(err)
	}
}
```

**Comment by godelized** [comment]
Hello, thanks for reporting this.

We indeed reproduced: when using `opt.AttributesToHighlight()`, the parameter `v ...string` of `AttributesToHighlight` will be `nil`.
If we pass `[]string{}...` directly to `AttributesToHighlight` it will be the empty array.

Here's a snippet of code that shows that we can use `opt.AttributesToHighlight([]string{}...)` to disable the highlighting.

I'd let our team decide if we need to introduce a custom value or not.

```go
package main

import (
	"encoding/json"
	"fmt"

	"github.com/algolia/algoliasearch-client-go/v3/algolia/opt"
	"github.com/algolia/algoliasearch-client-go/v3/algolia/search"
)

const (
	appID  = "******"
	apiKey = "******"
)

type Doc struct {
	ObjectID string `json:"objectID"`
	Content  string `json:"content"`
}

func main() {
	algoliaSearchClient := search.NewClient(appID, apiKey)
	index := algoliaSearchClient.InitIndex("highlight-test")

	_, err := index.SaveObject(Doc{ObjectID: "1", Content: "foo"})
	if err != nil {
		panic(err)
	}

	testWith(index, opt.AttributesToHighlight())
	testWith(index, opt.AttributesToHighlight([]string{}...))
}

func testWith(index *search.Index, attributesToHighlight *opt.AttributesToHighlightOption) {
	res, err := index.SetSettings(search.Settings{
		AttributesToHighlight: attributesToHighlight,
	})
	if err != nil {
		panic(err)
	}
	if err = res.Wait(); err != nil {
		panic(err)
	}

	searchRes, err := index.Search("foo")
	if err != nil {
		panic(err)
	}

	output, err := json.MarshalIndent(searchRes, "", "  ")
	if err != nil {
		panic(err)
	}
	fmt.Println(string(output))
}
```

**Comment by samouss** [comment]
Hello! The fix proposed by @godelized is probably good enough at the moment. The main reason is because it does work for `AttributesToHighlight` but also for every other list parameter that supports an empty list e.g. searchable attributes, attributes for faceting, ...

If we want to solve the overall problem with the proposed solution we have to expose one function for each parameter which doesn't seem legit to me. Ideally we should be able to differentiate values, empty values, nil values from the same function. Unfortunately, we can't for backward compatibility. That's why  for now I think the work around is better than good enough. How does it sounds to you?

**Comment by k-yomo** [comment]
Yeah, I missed that `opt.AttributesToHighlight([]string{}...)` works.  
I totally agree that we can't take the ideal way without breaking change.
Let me close this PR!
