### ISSUE TITLE
Proposal to explicitly allow multiple queries for Federated Search

### ISSUE THREAD

**Issue by somen440** [algolia/algoliasearch-client-go#707]
- Algolia Client Version: 3.26.1
- Language Version: ?.?.?

### Description

I'm looking for a way to handle both Japanese hiragana and katakana in search queries at the same time, and hit katakana results when searching in hiragana via `attributeForDistinct` . ( This is because specifying Japanese in the Index/Query Language may result in unintended behavior. )

For example, if I make the following request, I can get the expected value.

```
❯ curl -sL -X POST \
     -H "X-Algolia-API-Key: ${ALGOLIA_SEARCH_API_KEY}" \
     -H "X-Algolia-Application-Id: ${ALGOLIA_APPLICATION_ID}" \
     --data-binary '{ "params": "query=ほげ&query=ホゲ" }' \
    "https://${ALGOLIA_APPLICATION_ID}-dsn.algolia.net/1/indexes/${ALGOLIA_INDEX_NAME}/query"
```

I want to make this request through this client.
I've confirmed that this can be done in the following way.

```
        ...
        ...
	res, err := c.initIndex(req.Langage).Search(
		"ほげ", // query
		opt.ExtraOptions(map[string]interface{}{"query": "ホゲ"}),
	)
        ...
        ...
```

I feel that this method is not declarative and intuitive.

```
	res, err := c.initIndex(req.Langage).Search(
		"ほげ", // query
		opt.Query("ホゲ"),
	)
```

or

```
	res, err := c.initIndex(req.Langage).Search(
		"ほげ", // query
		opt.ExtraQuery("ホゲ"),
	)
```

I thought it would be nice to have something like that, but what do you think?

**Comment by somen440** [comment]
very sorry...
I confirmed that even if two query params are attached, it will win later.
I misunderstood the specifications. API `/1/indexes/${ALGOLIA_INDEX_NAME}/query` 
i use `/queries` ...

**Comment by samouss** [comment]
Hello! Indeed if we provide two times the `query` parameter the later always win. You can use the multi queries endpoint to perform two different searches with a different `query`. You can then pick results that are the more relevant for you.

From what I understood it's already what you're doing. I'm closing the issue but please reopen another one if you have other issues.
