### ISSUE TITLE
Using gzip compression breaks api calls after a lot of calls.

### ISSUE THREAD

**Issue by Mebby8448** [algolia/algoliasearch-client-go#742]
- Algolia Client Version: 3.31.0
- Language Version: Golang 1.21.0

### Description
Using gzip compression in the client leads to accumulating the addition of the same header `content-encoding: gzip` to each api call.
As a result of this after a lot of calls, you will get 494 errors from Algolia API on each call.

Output from Algolia search API Logs:
Host: xxxxxxxxxxx.algolia.net
User-Agent: Algolia for Go (3.31.0);Go (go1.21.1)
Transfer-Encoding: chunked
Connection: Keep-Alive
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: gzip
Content-Encoding: ...

### Steps To Reproduce
1. Add gzip encoding in the client
2. Call API N times
3. Check the header to the Aloglia API, after 2-3 calls. The headers accumulate

**Comment by Fluf22** [comment]
Thank you very much!
Sorry for the delay ☺️
