### ISSUE TITLE
Avoid unmarshalling QueryRes.Hits into json default types

### ISSUE THREAD

**Issue by georgantasp** [algolia/algoliasearch-client-go#743]
- Algolia Client Version: v3.30.1
- Language Version: 1.20

### Description

During the unmarshalling of the QueryRes object, the existing implementation will completely unmarshal each hit object into json [default types](https://pkg.go.dev/encoding/json#Unmarshal). As a result, the method `QueryRes.UnmarshalHits` _remarshals_ the default types just to unmarshal again into the users's desired type. For large result sets and/or large objects, this can be wasteful.

~PR incoming...~
[PR](https://github.com/algolia/algoliasearch-client-go/pull/744)

### Steps To Reproduce

```
res, _index.Search(query, params...)
algoliaObjectResults := []AlgoliaObject{}
res.UnmarshalHits(&algoliaObjectResults)
```

**Comment by millotp** [comment]
https://github.com/algolia/algoliasearch-client-go/pull/744#issuecomment-2320266903
