### ISSUE TITLE
Add `eventSubtype` to insights client

### ISSUE THREAD

**Issue by raed667** [algolia/algoliasearch-client-go#749]
- Algolia Client Version: `3.31.0`
- Language Version: `1.21.5`

### Description

According to this [documentation](https://www.algolia.com/doc/rest-api/insights/#method-param-eventsubtype) the insights API accepts an `eventSubtype` that seems to be missing from the package's type: 

```go 
type Event struct {
	EventType string    `json:"eventType"`
	EventName string    `json:"eventName"`
	Index     string    `json:"index"`
	UserToken string    `json:"userToken"`
	Timestamp time.Time `json:"-"`
	ObjectIDs []string  `json:"objectIDs,omitempty"`
	Positions []int     `json:"positions,omitempty"`
	QueryID   string    `json:"queryID,omitempty"`
	Filters   []string  `json:"filters,omitempty"`
}
``` 

This would be a useful parameter to support.

**Comment by vredens** [comment]
+1
