### ISSUE TITLE
Untyped function parameter

### ISSUE THREAD

**Issue by bengreenbank** [algolia/algoliasearch-client-go#765]
By accepting an `interface` here, we could encounter issues where incorrect parameters are passed to the function, see an example [here](https://github.com/algolia/go/pull/15400). Could we type it as an option instead?

https://github.com/algolia/algoliasearch-client-go/blob/64232385c99915e8dc51daa1fa4c753c2ab7e97a/algolia/search/index_settings.go#L11-L29

**Comment by millotp** [comment]
Hey, in v4 all parameters and options have strict types now, which introduces many breaking changes unfortunately
