### ISSUE TITLE
[bug]: insights events are missing fields such as price, currency and objectData

### ISSUE THREAD

**Issue by vredens** [algolia/algoliasearch-client-go#767]
### Description

Insights Events type is missing parameters when compared to the API spec https://www.algolia.com/doc/rest-api/insights/#tag/events/operation/pushEvents

- objectData
- price
- currency

and others.

This is preventing us to push this information to Algolia's insights API.

### Client

Insights

### Version

3

**Comment by jkaho** [comment]
@vredens hello! The latest version of the client should include the correct fields. Is there a reason you're unable to [upgrade to v4](https://www.algolia.com/doc/libraries/go/v4/upgrade/)?

**Comment by Fluf22** [comment]
@vredens hey 👋🏻 sorry we took so long to address the missing properties.
Tell me if something else is wrong!

Please note that some of these props are not strongly typed because they are polymorphic.
As a reminder: https://www.algolia.com/doc/rest-api/insights/#tag/events/operation/pushEvents
